# -*- coding: utf-8 -*-
"""hiMCM graph Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyU1PhML1CP6fUfjRKKCTvhunYQjcMsA
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from himcm.core import (
    calculate_sustainability_scores,
    analyze_previous_hosts,
    analyze_new_hosts,
    comprehensive_analysis,
    save_analysis_results,
    expand_model_for_multisport,
)


if __name__ == '__main__':
    # Read CSV and run full analysis using functions from himcm.core
    df = pd.read_csv('super_bowl_sustainability_data.csv')

    print("Dataset Overview:")
    print(df.head())
    print("\nDataset Info:")
    print(df.info())
    print("\nDataset Shape:", df.shape)

    print("Missing values in each column:")
    print(df.isnull().sum())

    df = calculate_sustainability_scores(df)

    print("Dataset with calculated scores (columns: Raw_Score, Sustainability_Z, Sustainability_Z_Scaled):")
    print(df[['City', 'State', 'Raw_Score', 'Sustainability_Z_Scaled']].head())

    previous_hosts_ranked = analyze_previous_hosts(df)
    new_hosts_ranked = analyze_new_hosts(df)
    all_ranked = comprehensive_analysis(df)

    save_analysis_results(df, previous_hosts_ranked, new_hosts_ranked, all_ranked)

    multisport_ranked = expand_model_for_multisport(df)

    # Visualize top cities
    df_ranked = df.sort_values('Sustainability_Z_Scaled', ascending=False)
    plt.figure(figsize=(10, 8))
    sns.set_theme(style="whitegrid")
    sns.barplot(data=df_ranked.head(12), y='City', x='Sustainability_Z_Scaled', palette='viridis')
    plt.title('Top Cities by Environmental Sustainability (Scaled Z)')
    plt.xlabel('Scaled Z Score (mean 50, sd 10)')
    plt.tight_layout()
    plt.show()

    numeric_cols = [c for c in ['Raw_Score', 'Sustainability_Z', 'Sustainability_Z_Scaled', 'Avg_Feb_Temp_F', 'Alltransit_Score', 'Renewable_Energy_Pct', 'Waste_Diversion_Pct'] if c in df.columns]
    if len(numeric_cols) >= 2:
        plt.figure(figsize=(8, 6))
        sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', center=0)
        plt.title('Correlation Matrix of Sustainability Factors')
        plt.show()

previous_hosts_ranked = analyze_previous_hosts(df)
if not previous_hosts_ranked.empty:
    best_previous_host = previous_hosts_ranked.iloc[0]
    print(f"\nRecommended previous host city: {best_previous_host['City']}, {best_previous_host['State']}")
    print(f"Scaled Z Score: {best_previous_host['Sustainability_Z_Scaled']}")


def analyze_new_hosts(df):
    """Analyze cities that have never hosted Super Bowl using scaled Z score"""
    previous_host_cities = ['New Orleans', 'Miami', 'Los Angeles', 'Tampa', 'Phoenix',
                           'Glendale', 'Atlanta', 'Houston', 'San Diego', 'Santa Clara',
                           'Inglewood', 'Las Vegas']

    new_hosts_df = df[~df['City'].isin(previous_host_cities)].copy()
    new_hosts_ranked = new_hosts_df.sort_values('Sustainability_Z_Scaled', ascending=False)

    print("=== PART 3b: NEW POTENTIAL HOST CITIES RANKING (by scaled Z score) ===")
    print(new_hosts_ranked[['City', 'State', 'Sustainability_Z_Scaled']].head(10))

    # Visualize top new potential hosts
    plt.figure(figsize=(10, 6))
    top_new_hosts = new_hosts_ranked.head(8)
    sns.barplot(data=top_new_hosts, x='Sustainability_Z_Scaled', y='City')
    plt.title('Top New Potential Host Cities Ranked by Sustainability (scaled Z)')
    plt.xlabel('Scaled Z Score (mean 50, sd 10)')
    plt.tight_layout()
    plt.show()

    return new_hosts_ranked


new_hosts_ranked = analyze_new_hosts(df)
if not new_hosts_ranked.empty:
    best_new_host = new_hosts_ranked.iloc[0]
    print(f"\nRecommended new host city: {best_new_host['City']}, {best_new_host['State']}")
    print(f"Scaled Z Score: {best_new_host['Sustainability_Z_Scaled']}")


def comprehensive_analysis(df):
    """Perform comprehensive analysis and create visualizations using the new columns"""

    # 1. Overall ranking of all cities by scaled Z
    all_cities_ranked = df.sort_values('Sustainability_Z_Scaled', ascending=False)

    print("=== COMPREHENSIVE RANKING OF ALL CITIES (by scaled Z) ===")
    print(all_cities_ranked[['City', 'State', 'Sustainability_Z_Scaled']].head(10))

    # 2. Correlation analysis: choose available numeric columns
    numeric_candidates = ['Raw_Score', 'Sustainability_Z', 'Sustainability_Z_Scaled', 'Avg_Feb_Temp_F',
                          'Alltransit_Score', 'Renewable_Energy_Pct', 'Waste_Diversion_Pct']
    available_numeric_cols = [c for c in numeric_candidates if c in df.columns]

    if len(available_numeric_cols) >= 2:
        plt.figure(figsize=(10, 8))
        correlation_matrix = df[available_numeric_cols].corr()
        sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0, square=True)
        plt.title('Correlation Matrix of Sustainability Factors')
        plt.tight_layout()
        plt.show()

    # 3. Sustainability score distribution (use scaled Z)
    if 'Sustainability_Z_Scaled' in df.columns:
        plt.figure(figsize=(12, 6))
        plt.subplot(1, 2, 1)
        plt.hist(df['Sustainability_Z_Scaled'], bins=15, alpha=0.7, edgecolor='black')
        plt.xlabel('Scaled Z Score')
        plt.ylabel('Frequency')
        plt.title('Distribution of Scaled Z Scores')

        plt.subplot(1, 2, 2)
        df.boxplot(column='Sustainability_Z_Scaled')
        plt.title('Box Plot of Scaled Z Scores')
        plt.tight_layout()
        plt.show()

    return all_cities_ranked


all_ranked = comprehensive_analysis(df)


def save_analysis_results(df, previous_hosts_ranked, new_hosts_ranked, all_ranked):
    """Save all analysis results to CSV files (updated to new column names)"""

    df.to_csv('super_bowl_with_sustainability_scores.csv', index=False)
    previous_hosts_ranked.to_csv('previous_hosts_ranked.csv', index=False)
    new_hosts_ranked.to_csv('new_potential_hosts_ranked.csv', index=False)
    all_ranked.to_csv('all_cities_sustainability_ranked.csv', index=False)

    # Save summary statistics of relevant numeric columns
    summary_cols = [c for c in ['Raw_Score', 'Sustainability_Z_Scaled', 'Alltransit_Score', 'Renewable_Energy_Pct', 'Waste_Diversion_Pct'] if c in df.columns]
    if summary_cols:
        summary_stats = df[summary_cols].describe()
        summary_stats.to_csv('sustainability_metrics_summary.csv')

    print("Analysis results saved to CSV files:")
    print("- super_bowl_with_sustainability_scores.csv")
    print("- previous_hosts_ranked.csv")
    print("- new_potential_hosts_ranked.csv")
    print("- all_cities_sustainability_ranked.csv")
    print("- sustainability_metrics_summary.csv")


save_analysis_results(df, previous_hosts_ranked, new_hosts_ranked, all_ranked)


# Model expansion for Part 4: Multi-sport events
def expand_model_for_multisport(df, extra_weights=None):
    """
    Expand the sustainability model for multi-sport events by adjusting weights.
    This re-runs the calculate_sustainability_scores with modified user_weights.
    """
    # Example: increase weights for infrastructure & legacy projects
    base_override = {
        'Green_Legacy_Projects': 0.20,
        'Alltransit_Score': 0.25,
        'Renewable_Energy_Pct': 0.25,
        'Env_Conditions': 0.20
    }
    if extra_weights:
        base_override.update(extra_weights)

    multisport_df = calculate_sustainability_scores(df, user_weights=base_override, env_overall_weight=0.25)
    multisport_ranked = multisport_df.sort_values('Sustainability_Z_Scaled', ascending=False)

    print("=== MULTI-SPORT EVENT RANKING (by scaled Z) ===")
    print(multisport_ranked[['City', 'State', 'Sustainability_Z_Scaled']].head(10))

    comparison = multisport_df[['City', 'State', 'Sustainability_Z_Scaled']].head(10)
    print("\nTop comparison for multi-sport scenario:")
    print(comparison)

    return multisport_ranked


multisport_ranked = expand_model_for_multisport(df)

# Visualize the results using Seaborn (top 12 cities)
df_ranked = df.sort_values('Sustainability_Z_Scaled', ascending=False)
plt.figure(figsize=(10, 8))
sns.set_theme(style="whitegrid")
sns.barplot(data=df_ranked.head(12), y='City', x='Sustainability_Z_Scaled', palette='viridis')
plt.title('Top Cities by Environmental Sustainability (Scaled Z)')
plt.xlabel('Scaled Z Score (mean 50, sd 10)')
plt.tight_layout()
plt.show()

# Generate a correlation heatmap to see how factors relate to the score
numeric_cols = [c for c in ['Raw_Score', 'Sustainability_Z', 'Sustainability_Z_Scaled', 'Avg_Feb_Temp_F', 'Alltransit_Score', 'Renewable_Energy_Pct', 'Waste_Diversion_Pct'] if c in df.columns]
if len(numeric_cols) >= 2:
    plt.figure(figsize=(8, 6))
    sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', center=0)
    plt.title('Correlation Matrix of Sustainability Factors')
    plt.show()